#!/usr/bin/perl
##
# Convert names and versions of distributions into ArchLinux package names
# and versions. Avoid printing duplicates package names.
##
# Input: [CPAN distribution name] [perl distribution/module version]
# Output: [ArchLinux package name] [arch pkg version]

use warnings;
use strict;
use English qw(-no_match_vars);

# Copied from CPANPLUS::Dist::Arch
sub dist_pkgname
{
    my ($name) = @_;
    my $orig = $name;

    # Package names should be lowercase and consist of alphanumeric
    # characters only (and hyphens!)...
    $name =~ tr/A-Z/a-z/;
    $name =~ tr/_+/-/; # _ and +'s converted to - (ie Tabbed-Text+Wrap)
    $name =~ tr/-a-z0-9+//cd; # Delete all other chars.
    $name =~ tr/-/-/s;

    # Delete leading or trailing hyphens...
    $name =~ s/\A-|-\z//g;

    die qq{Dist. name '$orig' completely violates packaging standards}
        unless $name;

    return "perl-$name";
}

sub dist_pkgver
{
    my ($version) = @_;

    # Package versions should be numbers and decimal points only...
    $version =~ tr/-/./;
    $version =~ tr/_0-9.-//cd;

    # Remove developer versions because pacman has no special logic
    # to compare them to regular versions like perl does.
    $version =~ s/_[^_]+\z//;

    $version =~ tr/_//d;  # delete other underscores
    $version =~ tr/././s; # only one period at a time
    $version =~ s/\A[.]|[.]\z//g; # shouldn't start or stop with a period

    return $version;
}

$OFS = " ";
$ORS = "\n";

my %seen;
while (<>) {
    my ($name, $ver) = split;
    next unless $name;

    $name = dist_pkgname($name);
    next if $seen{$name}++;

    if ($ver) {
        $ver = dist_pkgver($ver) if $ver;
        print $name, $ver;
    }
    else {
        print $name
    }
}
