#!/usr/bin/awk -f
##
# Give a list of dist/version pairs in STDIN and this
# will print out the dist/version pairs that are on cpan.

{
    cmd = "curl --silent http://search.cpan.org/dist/" $1 "/"
    while (cmd|getline html > 0) {
        if (html ~ /The distribution/ && html ~ /cannot be found/) next
    }
    close(cmd)
    print
}
