#!/bin/sh
##
# Print a list of perl module packages.
#
# Args: repository dirs name ("dbs/$dirname" is searched)
# Output: [perl package name] [package version] [packager email]

if [ $# -eq 0 ] ; then
    echo "Usage: $0 [db dir name]" 1>&2
    exit 1
fi

for dbdir ; do
    find "dbs/$dbdir" -name 'desc' | xargs awk -v repo="$dbdir" '
BEGIN { RS=""; FS="\n"; ORS="\n"; OFS="\t" }
$1 == "%NAME%" { if ($2 ~ /^perl|-perl$/) name = $2; else name = 0 }
$1 == "%VERSION%" { ver = $2 }
$1 == "%PACKAGER%" && name { 
    if (match($2, /<[^>]+>/)) {
        author = substr($2, RSTART+1, RLENGTH-2)
    }
    else author = $2
    gsub(/ /, "", author)
    print repo, name, ver, author
    name = 0
}
'
done
