#!/bin/sh
##
# Generate the list of core distributions.

if [ -z "$1" ] ; then
    echo "Usage: $0 [path to perl source directory]"
    exit 1
fi

./listdists $1 | ./distrename >core.dists
./listmods $1 | ./modoncpan >>core.dists
sort core.dists > core.dists.new
mv core.dists.new core.dists
