#!/usr/bin/perl -l
##
# Prints out a list of the modules inside the perl source's "lib" dir.
#
# Args: Path to the extracted perl source directory.
# Output: [module name]

use File::Find;

my $srcdir = shift @ARGV or die "Usage: $0 [perl source dir]\n";
my $libdir = "$srcdir/lib/";

die "failed to find $libdir directory" unless -d $libdir;

find({'no_chdir' => 1,
      'wanted' => sub {
          next unless s{\.pm\z}{};
          s{\A$libdir}{}; s{/}{::}g;
          print;
      }}, $libdir);
