#!/bin/sh
##
# Print a perl provides list for all the distributions bundled with perl.
##
# Arg: path to the perl source directory
# Output: a provides array suitable to insert into the perl package's PKGBUILD.

./dist2pkg core.dists | sort | ./fmtprovides
