#!/usr/bin/awk -f
##
# Rename distributions to their new names on CPAN.

BEGIN {
    map["List-Util"] = "Scalar-List-Utils"
    map["Text-Tabs"] = "Text-Tabs+Wrap"
    map["Cwd"] = "PathTools"
}

$1 in map { $1 = map[$1] }
1
